language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test

notifications:
  slack: giterdone4:tjH4PGpsNZLksCUcnlBXPjhh
    on_success: always
    on_failure: always

after_success:
    - coveralls