language: python
python:
    - "3.5"
before_install:
    - pip install portalocker
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test

notifications:
  slack: giterdone4:tjH4PGpsNZLksCUcnlBXPjhh
  #on_success: change
  #on_failure: change

after_success:
    - coveralls